#Smart reader makefile

#Probably only 'gcc' can be used if compiling with the board's toolchain.
CC = gcc

#For Windows
RM = cmd /C del

#For Linux
#RM = rm -f

SRC = ./src/main.c ./src/util.c ./src/setup.c ./src/inventory.c ./src/readercaps.c

INCLUDE = -I./inc/
LIBDEF = -L./lib/ -lNurApiRaspi -lm -lpthread
CFLAGS = -D_PLAT_RASPI -DNUR_EXPOSE_WIN32API 

OUTPUT = nurconrpi

all:
	$(CC) $(INCLUDE) $(CFLAGS) $(SRC) -o $(OUTPUT) $(LIBDEF)

clean:
	$(RM) $(OUTPUT)
