CC = gcc
RM = rm -f

SRC = ./src/main.c ./src/util.c ./src/menu.c ./src/setup.c ./src/scan.c ./src/inventory.c ./src/tags.c ./src/readercaps.c ./src/notification.c ./src/ethmenu.c

INCLUDE = -I./inc/
LIBDEF = -L./lib/ -lNurApix86 -lm -lpthread
BITNESS = -m32
CFLAGS = -D_PLAT_LINUX86 -DNUR_EXPOSE_WIN32API

OUTPUT = nurconx86

all:
	$(CC) $(INCLUDE) $(CFLAGS) $(SRC) $(BITNESS) -o $(OUTPUT) $(LIBDEF)

clean:
	$(RM) $(OUTPUT)
